/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ItpListAllResponsePaging
 */
public class ItpListAllResponsePagingTest {
    private final ItpListAllResponsePaging model = new ItpListAllResponsePaging();

    /**
     * Model tests for ItpListAllResponsePaging
     */
    @Test
    public void testItpListAllResponsePaging() {
        // TODO: test ItpListAllResponsePaging
    }

    /**
     * Test the property 'before'
     */
    @Test
    public void beforeTest() {
        // TODO: test before
    }

    /**
     * Test the property 'after'
     */
    @Test
    public void afterTest() {
        // TODO: test after
    }

}
