/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.RecipientGetWithdrawalByIdResponseBankAccount;
import com.konfigthis.client.model.RecipientGetWithdrawalByIdResponseMetadata;
import com.konfigthis.client.model.RecipientGetWithdrawalByIdResponseRecipient;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RecipientGetWithdrawalByIdResponse
 */
public class RecipientGetWithdrawalByIdResponseTest {
    private final RecipientGetWithdrawalByIdResponse model = new RecipientGetWithdrawalByIdResponse();

    /**
     * Model tests for RecipientGetWithdrawalByIdResponse
     */
    @Test
    public void testRecipientGetWithdrawalByIdResponse() {
        // TODO: test RecipientGetWithdrawalByIdResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'approvedAt'
     */
    @Test
    public void approvedAtTest() {
        // TODO: test approvedAt
    }

    /**
     * Test the property 'rejectedAt'
     */
    @Test
    public void rejectedAtTest() {
        // TODO: test rejectedAt
    }

    /**
     * Test the property 'paidAt'
     */
    @Test
    public void paidAtTest() {
        // TODO: test paidAt
    }

    /**
     * Test the property 'failedAt'
     */
    @Test
    public void failedAtTest() {
        // TODO: test failedAt
    }

    /**
     * Test the property 'pixKey'
     */
    @Test
    public void pixKeyTest() {
        // TODO: test pixKey
    }

    /**
     * Test the property 'bankAccount'
     */
    @Test
    public void bankAccountTest() {
        // TODO: test bankAccount
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
