/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.RecipientListBankAccountsResponseDataInnerMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RecipientListBankAccountsResponseDataInner
 */
public class RecipientListBankAccountsResponseDataInnerTest {
    private final RecipientListBankAccountsResponseDataInner model = new RecipientListBankAccountsResponseDataInner();

    /**
     * Model tests for RecipientListBankAccountsResponseDataInner
     */
    @Test
    public void testRecipientListBankAccountsResponseDataInner() {
        // TODO: test RecipientListBankAccountsResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'holderName'
     */
    @Test
    public void holderNameTest() {
        // TODO: test holderName
    }

    /**
     * Test the property 'holderTaxId'
     */
    @Test
    public void holderTaxIdTest() {
        // TODO: test holderTaxId
    }

    /**
     * Test the property 'holderType'
     */
    @Test
    public void holderTypeTest() {
        // TODO: test holderType
    }

    /**
     * Test the property 'branchNumber'
     */
    @Test
    public void branchNumberTest() {
        // TODO: test branchNumber
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'bankId'
     */
    @Test
    public void bankIdTest() {
        // TODO: test bankId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
