/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WebhookListAllResponseDataInnerDataDestination;
import com.konfigthis.client.model.WebhookListAllResponseDataInnerDataPayer;
import com.konfigthis.client.model.WebhookListAllResponseDataInnerDataSource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookListAllResponseDataInnerData
 */
public class WebhookListAllResponseDataInnerDataTest {
    private final WebhookListAllResponseDataInnerData model = new WebhookListAllResponseDataInnerData();

    /**
     * Model tests for WebhookListAllResponseDataInnerData
     */
    @Test
    public void testWebhookListAllResponseDataInnerData() {
        // TODO: test WebhookListAllResponseDataInnerData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'paidAmount'
     */
    @Test
    public void paidAmountTest() {
        // TODO: test paidAmount
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'processedAt'
     */
    @Test
    public void processedAtTest() {
        // TODO: test processedAt
    }

    /**
     * Test the property 'paidAt'
     */
    @Test
    public void paidAtTest() {
        // TODO: test paidAt
    }

    /**
     * Test the property 'failedAt'
     */
    @Test
    public void failedAtTest() {
        // TODO: test failedAt
    }

    /**
     * Test the property 'split'
     */
    @Test
    public void splitTest() {
        // TODO: test split
    }

    /**
     * Test the property 'payer'
     */
    @Test
    public void payerTest() {
        // TODO: test payer
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'destination'
     */
    @Test
    public void destinationTest() {
        // TODO: test destination
    }

}
