/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WebhookGetResponseData;
import com.konfigthis.client.model.WebhookGetResponseObject;
import com.konfigthis.client.model.WebhookGetResponseResponsesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookGetResponse
 */
public class WebhookGetResponseTest {
    private final WebhookGetResponse model = new WebhookGetResponse();

    /**
     * Model tests for WebhookGetResponse
     */
    @Test
    public void testWebhookGetResponse() {
        // TODO: test WebhookGetResponse
    }

    /**
     * Test the property 'responses'
     */
    @Test
    public void responsesTest() {
        // TODO: test responses
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'queuedAt'
     */
    @Test
    public void queuedAtTest() {
        // TODO: test queuedAt
    }

    /**
     * Test the property 'deliveredAt'
     */
    @Test
    public void deliveredAtTest() {
        // TODO: test deliveredAt
    }

    /**
     * Test the property 'failedAt'
     */
    @Test
    public void failedAtTest() {
        // TODO: test failedAt
    }

    /**
     * Test the property 'lastAttemptAt'
     */
    @Test
    public void lastAttemptAtTest() {
        // TODO: test lastAttemptAt
    }

    /**
     * Test the property 'nextAttemptAt'
     */
    @Test
    public void nextAttemptAtTest() {
        // TODO: test nextAttemptAt
    }

    /**
     * Test the property 'endpointId'
     */
    @Test
    public void endpointIdTest() {
        // TODO: test endpointId
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

}
