/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WebhookResendAttemptResponseData;
import com.konfigthis.client.model.WebhookResendAttemptResponseObject;
import com.konfigthis.client.model.WebhookResendAttemptResponseResponsesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * WebhookResendAttemptResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class WebhookResendAttemptResponse {
  public static final String SERIALIZED_NAME_RESPONSES = "responses";
  @SerializedName(SERIALIZED_NAME_RESPONSES)
  private List<WebhookResendAttemptResponseResponsesInner> responses = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_EVENT = "event";
  @SerializedName(SERIALIZED_NAME_EVENT)
  private String event;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private WebhookResendAttemptResponseObject _object;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  private String signature;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private WebhookResendAttemptResponseData data;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_QUEUED_AT = "queuedAt";
  @SerializedName(SERIALIZED_NAME_QUEUED_AT)
  private String queuedAt;

  public static final String SERIALIZED_NAME_DELIVERED_AT = "deliveredAt";
  @SerializedName(SERIALIZED_NAME_DELIVERED_AT)
  private String deliveredAt;

  public static final String SERIALIZED_NAME_FAILED_AT = "failedAt";
  @SerializedName(SERIALIZED_NAME_FAILED_AT)
  private Object failedAt = null;

  public static final String SERIALIZED_NAME_LAST_ATTEMPT_AT = "lastAttemptAt";
  @SerializedName(SERIALIZED_NAME_LAST_ATTEMPT_AT)
  private String lastAttemptAt;

  public static final String SERIALIZED_NAME_NEXT_ATTEMPT_AT = "nextAttemptAt";
  @SerializedName(SERIALIZED_NAME_NEXT_ATTEMPT_AT)
  private Object nextAttemptAt = null;

  public static final String SERIALIZED_NAME_ENDPOINT_ID = "endpointId";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_ID)
  private String endpointId;

  public static final String SERIALIZED_NAME_ORGANIZATION_ID = "organizationId";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ID)
  private String organizationId;

  public WebhookResendAttemptResponse() {
  }

  public WebhookResendAttemptResponse responses(List<WebhookResendAttemptResponseResponsesInner> responses) {
    
    
    
    
    this.responses = responses;
    return this;
  }

  public WebhookResendAttemptResponse addResponsesItem(WebhookResendAttemptResponseResponsesInner responsesItem) {
    if (this.responses == null) {
      this.responses = new ArrayList<>();
    }
    this.responses.add(responsesItem);
    return this;
  }

   /**
   * Get responses
   * @return responses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WebhookResendAttemptResponseResponsesInner> getResponses() {
    return responses;
  }


  public void setResponses(List<WebhookResendAttemptResponseResponsesInner> responses) {
    
    
    
    this.responses = responses;
  }


  public WebhookResendAttemptResponse id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "89f4209f-b574-4582-86b6-98584b4f65ef", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public WebhookResendAttemptResponse event(String event) {
    
    
    
    
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "payment.paid", value = "")

  public String getEvent() {
    return event;
  }


  public void setEvent(String event) {
    
    
    
    this.event = event;
  }


  public WebhookResendAttemptResponse _object(WebhookResendAttemptResponseObject _object) {
    
    
    
    
    this._object = _object;
    return this;
  }

   /**
   * Get _object
   * @return _object
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WebhookResendAttemptResponseObject getObject() {
    return _object;
  }


  public void setObject(WebhookResendAttemptResponseObject _object) {
    
    
    
    this._object = _object;
  }


  public WebhookResendAttemptResponse signature(String signature) {
    
    
    
    
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "e91aa3f03c7699db37e070ad4224a15c7b39dd383d2b0aef6f270f0a10d42772", value = "")

  public String getSignature() {
    return signature;
  }


  public void setSignature(String signature) {
    
    
    
    this.signature = signature;
  }


  public WebhookResendAttemptResponse data(WebhookResendAttemptResponseData data) {
    
    
    
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WebhookResendAttemptResponseData getData() {
    return data;
  }


  public void setData(WebhookResendAttemptResponseData data) {
    
    
    
    this.data = data;
  }


  public WebhookResendAttemptResponse status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DELIVERED", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public WebhookResendAttemptResponse createdAt(String createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-06T11:48:21Z", value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public WebhookResendAttemptResponse queuedAt(String queuedAt) {
    
    
    
    
    this.queuedAt = queuedAt;
    return this;
  }

   /**
   * Get queuedAt
   * @return queuedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-06T11:48:22Z", value = "")

  public String getQueuedAt() {
    return queuedAt;
  }


  public void setQueuedAt(String queuedAt) {
    
    
    
    this.queuedAt = queuedAt;
  }


  public WebhookResendAttemptResponse deliveredAt(String deliveredAt) {
    
    
    
    
    this.deliveredAt = deliveredAt;
    return this;
  }

   /**
   * Get deliveredAt
   * @return deliveredAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-06T11:49:03Z", value = "")

  public String getDeliveredAt() {
    return deliveredAt;
  }


  public void setDeliveredAt(String deliveredAt) {
    
    
    
    this.deliveredAt = deliveredAt;
  }


  public WebhookResendAttemptResponse failedAt(Object failedAt) {
    
    
    
    
    this.failedAt = failedAt;
    return this;
  }

   /**
   * Get failedAt
   * @return failedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getFailedAt() {
    return failedAt;
  }


  public void setFailedAt(Object failedAt) {
    
    
    
    this.failedAt = failedAt;
  }


  public WebhookResendAttemptResponse lastAttemptAt(String lastAttemptAt) {
    
    
    
    
    this.lastAttemptAt = lastAttemptAt;
    return this;
  }

   /**
   * Get lastAttemptAt
   * @return lastAttemptAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-06-06T11:49:01Z", value = "")

  public String getLastAttemptAt() {
    return lastAttemptAt;
  }


  public void setLastAttemptAt(String lastAttemptAt) {
    
    
    
    this.lastAttemptAt = lastAttemptAt;
  }


  public WebhookResendAttemptResponse nextAttemptAt(Object nextAttemptAt) {
    
    
    
    
    this.nextAttemptAt = nextAttemptAt;
    return this;
  }

   /**
   * Get nextAttemptAt
   * @return nextAttemptAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getNextAttemptAt() {
    return nextAttemptAt;
  }


  public void setNextAttemptAt(Object nextAttemptAt) {
    
    
    
    this.nextAttemptAt = nextAttemptAt;
  }


  public WebhookResendAttemptResponse endpointId(String endpointId) {
    
    
    
    
    this.endpointId = endpointId;
    return this;
  }

   /**
   * Get endpointId
   * @return endpointId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "33d8034f-6e13-4d15-b1b4-d88fcced590d", value = "")

  public String getEndpointId() {
    return endpointId;
  }


  public void setEndpointId(String endpointId) {
    
    
    
    this.endpointId = endpointId;
  }


  public WebhookResendAttemptResponse organizationId(String organizationId) {
    
    
    
    
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "bd0b3148-8772-4854-8a97-be409ed1ffa8", value = "")

  public String getOrganizationId() {
    return organizationId;
  }


  public void setOrganizationId(String organizationId) {
    
    
    
    this.organizationId = organizationId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WebhookResendAttemptResponse instance itself
   */
  public WebhookResendAttemptResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookResendAttemptResponse webhookResendAttemptResponse = (WebhookResendAttemptResponse) o;
    return Objects.equals(this.responses, webhookResendAttemptResponse.responses) &&
        Objects.equals(this.id, webhookResendAttemptResponse.id) &&
        Objects.equals(this.event, webhookResendAttemptResponse.event) &&
        Objects.equals(this._object, webhookResendAttemptResponse._object) &&
        Objects.equals(this.signature, webhookResendAttemptResponse.signature) &&
        Objects.equals(this.data, webhookResendAttemptResponse.data) &&
        Objects.equals(this.status, webhookResendAttemptResponse.status) &&
        Objects.equals(this.createdAt, webhookResendAttemptResponse.createdAt) &&
        Objects.equals(this.queuedAt, webhookResendAttemptResponse.queuedAt) &&
        Objects.equals(this.deliveredAt, webhookResendAttemptResponse.deliveredAt) &&
        Objects.equals(this.failedAt, webhookResendAttemptResponse.failedAt) &&
        Objects.equals(this.lastAttemptAt, webhookResendAttemptResponse.lastAttemptAt) &&
        Objects.equals(this.nextAttemptAt, webhookResendAttemptResponse.nextAttemptAt) &&
        Objects.equals(this.endpointId, webhookResendAttemptResponse.endpointId) &&
        Objects.equals(this.organizationId, webhookResendAttemptResponse.organizationId)&&
        Objects.equals(this.additionalProperties, webhookResendAttemptResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(responses, id, event, _object, signature, data, status, createdAt, queuedAt, deliveredAt, failedAt, lastAttemptAt, nextAttemptAt, endpointId, organizationId, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookResendAttemptResponse {\n");
    sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    queuedAt: ").append(toIndentedString(queuedAt)).append("\n");
    sb.append("    deliveredAt: ").append(toIndentedString(deliveredAt)).append("\n");
    sb.append("    failedAt: ").append(toIndentedString(failedAt)).append("\n");
    sb.append("    lastAttemptAt: ").append(toIndentedString(lastAttemptAt)).append("\n");
    sb.append("    nextAttemptAt: ").append(toIndentedString(nextAttemptAt)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("responses");
    openapiFields.add("id");
    openapiFields.add("event");
    openapiFields.add("object");
    openapiFields.add("signature");
    openapiFields.add("data");
    openapiFields.add("status");
    openapiFields.add("createdAt");
    openapiFields.add("queuedAt");
    openapiFields.add("deliveredAt");
    openapiFields.add("failedAt");
    openapiFields.add("lastAttemptAt");
    openapiFields.add("nextAttemptAt");
    openapiFields.add("endpointId");
    openapiFields.add("organizationId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to WebhookResendAttemptResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!WebhookResendAttemptResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookResendAttemptResponse is not found in the empty JSON string", WebhookResendAttemptResponse.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("responses") != null && !jsonObj.get("responses").isJsonNull()) {
        JsonArray jsonArrayresponses = jsonObj.getAsJsonArray("responses");
        if (jsonArrayresponses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("responses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `responses` to be an array in the JSON string but got `%s`", jsonObj.get("responses").toString()));
          }

          // validate the optional field `responses` (array)
          for (int i = 0; i < jsonArrayresponses.size(); i++) {
            WebhookResendAttemptResponseResponsesInner.validateJsonObject(jsonArrayresponses.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("event") != null && !jsonObj.get("event").isJsonNull()) && !jsonObj.get("event").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event").toString()));
      }
      // validate the optional field `object`
      if (jsonObj.get("object") != null && !jsonObj.get("object").isJsonNull()) {
        WebhookResendAttemptResponseObject.validateJsonObject(jsonObj.getAsJsonObject("object"));
      }
      if ((jsonObj.get("signature") != null && !jsonObj.get("signature").isJsonNull()) && !jsonObj.get("signature").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signature` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signature").toString()));
      }
      // validate the optional field `data`
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        WebhookResendAttemptResponseData.validateJsonObject(jsonObj.getAsJsonObject("data"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("queuedAt") != null && !jsonObj.get("queuedAt").isJsonNull()) && !jsonObj.get("queuedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queuedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queuedAt").toString()));
      }
      if ((jsonObj.get("deliveredAt") != null && !jsonObj.get("deliveredAt").isJsonNull()) && !jsonObj.get("deliveredAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deliveredAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deliveredAt").toString()));
      }
      if ((jsonObj.get("lastAttemptAt") != null && !jsonObj.get("lastAttemptAt").isJsonNull()) && !jsonObj.get("lastAttemptAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastAttemptAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastAttemptAt").toString()));
      }
      if ((jsonObj.get("endpointId") != null && !jsonObj.get("endpointId").isJsonNull()) && !jsonObj.get("endpointId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endpointId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endpointId").toString()));
      }
      if ((jsonObj.get("organizationId") != null && !jsonObj.get("organizationId").isJsonNull()) && !jsonObj.get("organizationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organizationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organizationId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookResendAttemptResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookResendAttemptResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookResendAttemptResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookResendAttemptResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookResendAttemptResponse>() {
           @Override
           public void write(JsonWriter out, WebhookResendAttemptResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookResendAttemptResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             WebhookResendAttemptResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WebhookResendAttemptResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WebhookResendAttemptResponse
  * @throws IOException if the JSON string is invalid with respect to WebhookResendAttemptResponse
  */
  public static WebhookResendAttemptResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookResendAttemptResponse.class);
  }

 /**
  * Convert an instance of WebhookResendAttemptResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

