/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BankTransferApi
 */
@Disabled
public class BankTransferApiTest {

    private static BankTransferApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BankTransferApi(apiClient);
    }

    /**
     * Retrieve a Bank Transfer
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBankTransferTest() throws ApiException {
        String bankTransferId = null;
        Object response = api.getBankTransfer(bankTransferId)
                .execute();
        // TODO: test validations
    }

    /**
     * List all Bank Transfers
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllBankTransfersTest() throws ApiException {
        String limit = null;
        String before = null;
        String after = null;
        Object response = api.listAllBankTransfers()
                .limit(limit)
                .before(before)
                .after(after)
                .execute();
        // TODO: test validations
    }

}
