/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ItpCreatePaymentInstructionRequest;
import com.konfigthis.client.model.ItpCreatePaymentInstructionResponse;
import com.konfigthis.client.model.ItpGetItpResponse;
import com.konfigthis.client.model.ItpListAllResponse;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestMetadataInner;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestPayer;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestSplitInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItpApi
 */
@Disabled
public class ItpApiTest {

    private static ItpApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ItpApi(apiClient);
    }

    /**
     * Create an ITP
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPaymentInstructionTest() throws ApiException {
        Integer amount = null;
        QrCodeGenerateQrCodeRequestPayer payer = null;
        String code = null;
        List<QrCodeGenerateQrCodeRequestSplitInner> split = null;
        List<QrCodeGenerateQrCodeRequestMetadataInner> metadata = null;
        ItpCreatePaymentInstructionResponse response = api.createPaymentInstruction(amount, payer)
                .code(code)
                .split(split)
                .metadata(metadata)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve an ITP
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getItpTest() throws ApiException {
        String id = null;
        ItpGetItpResponse response = api.getItp(id)
                .execute();
        // TODO: test validations
    }

    /**
     * List all ITPs
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        Integer limit = null;
        String before = null;
        String after = null;
        ItpListAllResponse response = api.listAll()
                .limit(limit)
                .before(before)
                .after(after)
                .execute();
        // TODO: test validations
    }

}
