/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequest;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestMetadataInner;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestPayer;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestSplitInner;
import com.konfigthis.client.model.QrCodeGenerateQrCodeResponse;
import com.konfigthis.client.model.QrCodeGetQrCodeByIdResponse;
import com.konfigthis.client.model.QrCodeListAllResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QrCodeApi
 */
@Disabled
public class QrCodeApiTest {

    private static QrCodeApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new QrCodeApi(apiClient);
    }

    /**
     * Create a Pix QR Code
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateQrCodeTest() throws ApiException {
        Integer amount = null;
        String code = null;
        QrCodeGenerateQrCodeRequestPayer payer = null;
        List<QrCodeGenerateQrCodeRequestSplitInner> split = null;
        List<QrCodeGenerateQrCodeRequestMetadataInner> metadata = null;
        QrCodeGenerateQrCodeResponse response = api.generateQrCode(amount)
                .code(code)
                .payer(payer)
                .split(split)
                .metadata(metadata)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a Pix QR Code
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQrCodeByIdTest() throws ApiException {
        String id = null;
        QrCodeGetQrCodeByIdResponse response = api.getQrCodeById(id)
                .execute();
        // TODO: test validations
    }

    /**
     * List all Pix QR Codes
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        Integer limit = null;
        String before = null;
        String after = null;
        QrCodeListAllResponse response = api.listAll()
                .limit(limit)
                .before(before)
                .after(after)
                .execute();
        // TODO: test validations
    }

}
