/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.TokenGenerateAccessTokenRequest;
import com.konfigthis.client.model.TokenGenerateAccessTokenResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokenApi
 */
@Disabled
public class TokenApiTest {

    private static TokenApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TokenApi(apiClient);
    }

    /**
     * Create an Access Token
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateAccessTokenTest() throws ApiException {
        String refreshToken = null;
        TokenGenerateAccessTokenResponse response = api.generateAccessToken(refreshToken)
                .execute();
        // TODO: test validations
    }

}
