/*
 * Developer API
 * At Sqala, we believe that everyone deserves access to financial services, and we are committed to providing secure and reliable payment solutions to clients who may have been overlooked by traditional financial institutions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.ItpCreatePaymentInstructionRequest;
import com.konfigthis.client.model.ItpCreatePaymentInstructionResponse;
import com.konfigthis.client.model.ItpGetItpResponse;
import com.konfigthis.client.model.ItpListAllResponse;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestMetadataInner;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestPayer;
import com.konfigthis.client.model.QrCodeGenerateQrCodeRequestSplitInner;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class ItpApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ItpApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public ItpApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createPaymentInstructionCall(ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = itpCreatePaymentInstructionRequest;

        // create path and map variables
        String localVarPath = "/itp-payments";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "sec0" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createPaymentInstructionValidateBeforeCall(ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest, final ApiCallback _callback) throws ApiException {
        return createPaymentInstructionCall(itpCreatePaymentInstructionRequest, _callback);

    }


    private ApiResponse<ItpCreatePaymentInstructionResponse> createPaymentInstructionWithHttpInfo(ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest) throws ApiException {
        okhttp3.Call localVarCall = createPaymentInstructionValidateBeforeCall(itpCreatePaymentInstructionRequest, null);
        Type localVarReturnType = new TypeToken<ItpCreatePaymentInstructionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createPaymentInstructionAsync(ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest, final ApiCallback<ItpCreatePaymentInstructionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createPaymentInstructionValidateBeforeCall(itpCreatePaymentInstructionRequest, _callback);
        Type localVarReturnType = new TypeToken<ItpCreatePaymentInstructionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreatePaymentInstructionRequestBuilder {
        private final Integer amount;
        private final QrCodeGenerateQrCodeRequestPayer payer;
        private String code;
        private List<QrCodeGenerateQrCodeRequestSplitInner> split;
        private List<QrCodeGenerateQrCodeRequestMetadataInner> metadata;

        private CreatePaymentInstructionRequestBuilder(Integer amount, QrCodeGenerateQrCodeRequestPayer payer) {
            this.amount = amount;
            this.payer = payer;
        }

        /**
         * Set code
         * @param code Unique identifier for the object in your system. (optional)
         * @return CreatePaymentInstructionRequestBuilder
         */
        public CreatePaymentInstructionRequestBuilder code(String code) {
            this.code = code;
            return this;
        }
        
        /**
         * Set split
         * @param split This object represents a list of recipients who will receive part of the payment. (optional)
         * @return CreatePaymentInstructionRequestBuilder
         */
        public CreatePaymentInstructionRequestBuilder split(List<QrCodeGenerateQrCodeRequestSplitInner> split) {
            this.split = split;
            return this;
        }
        
        /**
         * Set metadata
         * @param metadata Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. (optional)
         * @return CreatePaymentInstructionRequestBuilder
         */
        public CreatePaymentInstructionRequestBuilder metadata(List<QrCodeGenerateQrCodeRequestMetadataInner> metadata) {
            this.metadata = metadata;
            return this;
        }
        
        /**
         * Build call for createPaymentInstruction
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest = buildBodyParams();
            return createPaymentInstructionCall(itpCreatePaymentInstructionRequest, _callback);
        }

        private ItpCreatePaymentInstructionRequest buildBodyParams() {
            ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest = new ItpCreatePaymentInstructionRequest();
            itpCreatePaymentInstructionRequest.code(this.code);
            itpCreatePaymentInstructionRequest.amount(this.amount);
            itpCreatePaymentInstructionRequest.payer(this.payer);
            itpCreatePaymentInstructionRequest.split(this.split);
            itpCreatePaymentInstructionRequest.metadata(this.metadata);
            return itpCreatePaymentInstructionRequest;
        }

        /**
         * Execute createPaymentInstruction request
         * @return ItpCreatePaymentInstructionResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public ItpCreatePaymentInstructionResponse execute() throws ApiException {
            ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest = buildBodyParams();
            ApiResponse<ItpCreatePaymentInstructionResponse> localVarResp = createPaymentInstructionWithHttpInfo(itpCreatePaymentInstructionRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute createPaymentInstruction request with HTTP info returned
         * @return ApiResponse&lt;ItpCreatePaymentInstructionResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ItpCreatePaymentInstructionResponse> executeWithHttpInfo() throws ApiException {
            ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest = buildBodyParams();
            return createPaymentInstructionWithHttpInfo(itpCreatePaymentInstructionRequest);
        }

        /**
         * Execute createPaymentInstruction request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ItpCreatePaymentInstructionResponse> _callback) throws ApiException {
            ItpCreatePaymentInstructionRequest itpCreatePaymentInstructionRequest = buildBodyParams();
            return createPaymentInstructionAsync(itpCreatePaymentInstructionRequest, _callback);
        }
    }

    /**
     * Create an ITP
     * 
     * @return CreatePaymentInstructionRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
     </table>
     */
    public CreatePaymentInstructionRequestBuilder createPaymentInstruction(Integer amount, QrCodeGenerateQrCodeRequestPayer payer) throws IllegalArgumentException {
        if (amount == null) throw new IllegalArgumentException("\"amount\" is required but got null");
        if (payer == null) throw new IllegalArgumentException("\"payer\" is required but got null");
        return new CreatePaymentInstructionRequestBuilder(amount, payer);
    }
    private okhttp3.Call getItpCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/itp-payments/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "sec0" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getItpValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getItp(Async)");
        }

        return getItpCall(id, _callback);

    }


    private ApiResponse<ItpGetItpResponse> getItpWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getItpValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ItpGetItpResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getItpAsync(String id, final ApiCallback<ItpGetItpResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getItpValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ItpGetItpResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetItpRequestBuilder {
        private final String id;

        private GetItpRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getItp
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getItpCall(id, _callback);
        }


        /**
         * Execute getItp request
         * @return ItpGetItpResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public ItpGetItpResponse execute() throws ApiException {
            ApiResponse<ItpGetItpResponse> localVarResp = getItpWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getItp request with HTTP info returned
         * @return ApiResponse&lt;ItpGetItpResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ItpGetItpResponse> executeWithHttpInfo() throws ApiException {
            return getItpWithHttpInfo(id);
        }

        /**
         * Execute getItp request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ItpGetItpResponse> _callback) throws ApiException {
            return getItpAsync(id, _callback);
        }
    }

    /**
     * Retrieve an ITP
     * 
     * @param id Unique identifier for the object. (required)
     * @return GetItpRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
     </table>
     */
    public GetItpRequestBuilder getItp(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetItpRequestBuilder(id);
    }
    private okhttp3.Call listAllCall(Integer limit, String before, String after, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/itp-payments";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (before != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("before", before));
        }

        if (after != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("after", after));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "sec0" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listAllValidateBeforeCall(Integer limit, String before, String after, final ApiCallback _callback) throws ApiException {
        return listAllCall(limit, before, after, _callback);

    }


    private ApiResponse<ItpListAllResponse> listAllWithHttpInfo(Integer limit, String before, String after) throws ApiException {
        okhttp3.Call localVarCall = listAllValidateBeforeCall(limit, before, after, null);
        Type localVarReturnType = new TypeToken<ItpListAllResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listAllAsync(Integer limit, String before, String after, final ApiCallback<ItpListAllResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listAllValidateBeforeCall(limit, before, after, _callback);
        Type localVarReturnType = new TypeToken<ItpListAllResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ListAllRequestBuilder {
        private Integer limit;
        private String before;
        private String after;

        private ListAllRequestBuilder() {
        }

        /**
         * Set limit
         * @param limit A limit on the number of objects to be returned, between 1 and 50. (optional, default to 10)
         * @return ListAllRequestBuilder
         */
        public ListAllRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set before
         * @param before A cursor for use in pagination. &#x60;&#x60;&#x60;before&#x60;&#x60;&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 50 objects, starting with &#x60;&#x60;&#x60;obj_bar&#x60;&#x60;&#x60;, your subsequent call can include &#x60;&#x60;&#x60;before&#x3D;obj_bar&#x60;&#x60;&#x60; in order to fetch the previous page of the list. (optional)
         * @return ListAllRequestBuilder
         */
        public ListAllRequestBuilder before(String before) {
            this.before = before;
            return this;
        }
        
        /**
         * Set after
         * @param after A cursor for use in pagination. after is an object ID that defines your place in the list. For instance, if you make a list request and receive 50 objects, ending with obj_foo, your subsequent call can include after&#x3D;obj_foo in order to fetch the next page of the list. (optional)
         * @return ListAllRequestBuilder
         */
        public ListAllRequestBuilder after(String after) {
            this.after = after;
            return this;
        }
        
        /**
         * Build call for listAll
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listAllCall(limit, before, after, _callback);
        }


        /**
         * Execute listAll request
         * @return ItpListAllResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public ItpListAllResponse execute() throws ApiException {
            ApiResponse<ItpListAllResponse> localVarResp = listAllWithHttpInfo(limit, before, after);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute listAll request with HTTP info returned
         * @return ApiResponse&lt;ItpListAllResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ItpListAllResponse> executeWithHttpInfo() throws ApiException {
            return listAllWithHttpInfo(limit, before, after);
        }

        /**
         * Execute listAll request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ItpListAllResponse> _callback) throws ApiException {
            return listAllAsync(limit, before, after, _callback);
        }
    }

    /**
     * List all ITPs
     * 
     * @return ListAllRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 200 </td><td>  -  </td></tr>
     </table>
     */
    public ListAllRequestBuilder listAll() throws IllegalArgumentException {
        return new ListAllRequestBuilder();
    }
}
